### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by slothdabski** [CleanDroidOS/manifest#1]
Wouldn't KangDroidOS be a more appropriate name for this rom?

**Comment by thephotogenicbug** [comment]
lamo

**Comment by iamsaalim** [comment]
Well it's the correct name 😉

**Comment by Shobhit007** [comment]
Truth lol

**Comment by Fluffy28** [comment]
**LMFAO**

**Comment by DarkDroidDev** [comment]
> Wouldn't KangDroidOS be a more appropriate name for this rom?

surely you have opened the issue on the wrong repo, let me help you find the right one, probably here:  https://github.com/slothdabski?tab=repositories

**Comment by slothdabski** [comment]
> > Wouldn't KangDroidOS be a more appropriate name for this rom?
> 
> surely you have opened the issue on the wrong repo, let me help you find the right one, probably here: https://github.com/slothdabski?tab=repositories

Wow great comeback, I can see why it took 3 weeks to come up with that one!

**Comment by DarkDroidDev** [comment]
> > > Wouldn't KangDroidOS be a more appropriate name for this rom?
> > 
> > 
> > surely you have opened the issue on the wrong repo, let me help you find the right one, probably here: https://github.com/slothdabski?tab=repositories
> 
> Wow great comeback, I can see why it took 3 weeks to come up with that one!

Perfect
